{% set name = "feedfinder2" %}
{% set version = "0.0.4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '3701ee01a6c85f8b865a049c30ba0b4608858c803fe8e30d1d289fdbe89d0efe'

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - six
    - requests
    - beautifulsoup4

test:
  requires:
    - python {{ python_min }}
  imports:
    - feedfinder2


about:
  home: https://github.com/dfm/feedfinder2
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Find the feed URLs for a website.
  description: "This is a Python library for finding links feeds on a website."
  dev_url: 'https://github.com/dfm/feedfinder2'

extra:
  recipe-maintainers:
    - ganeshhubale
    - synapticarbors
